export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST';
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS';
export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL';
export const EMPLOYEE_LOGIN_RESET = 'EMPLOYEE_LOGIN_RESET ';

export const EMPLOYEE_FETCH_REQUEST = 'EMPLOYEE_FETCH_REQUEST';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_FETCH_FAIL = 'EMPLOYEE_FETCH_FAIL';
export const EMPLOYEE_FETCH_RESET = 'EMPLOYEE_FETCH_RESET ';
