export const PROJECTS_FETCH_REQUEST = 'PROJECTS_FETCH_REQUEST';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_FAIL = 'PROJECTS_FETCH_FAIL';
export const PROJECTS_FETCH_RESET = 'PROJECTS_FETCH_RESET';

// export const ACTIVE_PROJECTS_FETCH_REQUEST = 'ACTIVE_PROJECTS_FETCH_REQUEST';
// export const ACTIVE_PROJECTS_FETCH_SUCCESS = 'ACTIVE_PROJECTS_FETCH_SUCCESS';
// export const ACTIVE_PROJECTS_FETCH_FAIL = 'ACTIVE_PROJECTS_FETCH_FAIL';
// export const ACTIVE_PROJECTS_FETCH_RESET = 'ACTIVE_PROJECTS_FETCH_RESET';

export const PROJECT_FETCH_REQUEST = 'PROJECT_FETCH_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_FETCH_FAIL = 'PROJECT_FETCH_FAIL';
export const PROJECT_FETCH_RESET = 'PROJECT_FETCH_RESET';

export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAIL = 'PROJECT_ADD_FAIL';
export const PROJECT_ADD_RESET = 'PROJECT_ADD_RESET';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';
export const PROJECT_DELETE_RESET = 'PROJECT_DELETE_RESET';
