export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL';
export const TASK_ADD_RESET = 'TASK_ADD_RESET';

export const TASK_FETCH_REQUEST = 'TASK_FETCH_REQUEST';
export const TASK_FETCH_SUCCESS = 'TASK_FETCH_SUCCESS';
export const TASK_FETCH_FAIL = 'TASK_FETCH_FAIL';
export const TASK_FETCH_RESET = 'TASK_FETCH_RESET';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
