export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL';
export const TASK_ADD_RESET = 'TASK_ADD_RESET';

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL';
export const TASK_UPDATE_RESET = 'TASK_UPDATE_RESET';

export const TASK_FETCH_REQUEST = 'TASK_FETCH_REQUEST';
export const TASK_FETCH_SUCCESS = 'TASK_FETCH_SUCCESS';
export const TASK_FETCH_FAIL = 'TASK_FETCH_FAIL';
export const TASK_FETCH_RESET = 'TASK_FETCH_RESET';

export const TASK_EMPLOYEE_ADD_REQUEST = 'TASK_EMPLOYEE_ADD_REQUEST';
export const TASK_EMPLOYEE_ADD_SUCCESS = 'TASK_EMPLOYEE_ADD_SUCCESS';
export const TASK_EMPLOYEE_ADD_FAIL = 'TASK_EMPLOYEE_ADD_FAIL';
export const TASK_EMPLOYEE_ADD_RESET = 'TASK_EMPLOYEE_ADD_RESET';

export const TASK_EMPLOYEE_REMOVE_REQUEST = 'TASK_EMPLOYEE_REMOVE_REQUEST';
export const TASK_EMPLOYEE_REMOVE_SUCCESS = 'TASK_EMPLOYEE_REMOVE_SUCCESS';
export const TASK_EMPLOYEE_REMOVE_FAIL = 'TASK_EMPLOYEE_REMOVE_FAIL';
export const TASK_EMPLOYEE_REMOVE_RESET = 'TASK_EMPLOYEE_REMOVE_RESET';

export const TASKS_FETCH_REQUEST = 'TASKS_FETCH_REQUEST';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASKS_FETCH_FAIL = 'TASKS_FETCH_FAIL';
export const TASKS_FETCH_RESET = 'TASKS_FETCH_RESET';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
